import type { LLMProvider } from './types.js'; import type { ModelDescriptor,ProviderCapabilities,ProviderCredential,ProviderGenerateRequest,ProviderResponse,ProviderStreamChunk } from '@espera/shared'; import { endpoint,normalizeBaseUrl,safeFetch,statusError,ProviderError } from './http.js';
export class GeminiProvider implements LLMProvider { readonly id='gemini';readonly name='Google Gemini';readonly defaultBaseUrl='https://generativelanguage.googleapis.com/v1beta';
 base(c?:ProviderCredential){return normalizeBaseUrl(c?.endpointUrl,this.defaultBaseUrl)}
 async listModels(c?:ProviderCredential):Promise<ModelDescriptor[]>{if(!c?.apiKey)return[];const r=await safeFetch(endpoint(this.base(c),'models'),{headers:{'x-goog-api-key':c.apiKey}},c.apiKey);if(!r.ok)throw statusError(r.status);const d:any=await r.json();return(d.models||[]).filter((m:any)=>(m.supportedGenerationMethods||[]).includes('generateContent')).map((m:any)=>({id:String(m.name).replace(/^models\//,''),name:m.displayName||m.name,contextWindow:m.inputTokenLimit||0,supportsStreaming:true,available:true}))}
 async validateCredential(c:ProviderCredential){try{await this.listModels(c);return true}catch{return false}}
 payload(q:ProviderGenerateRequest){const sys=q.messages.filter(m=>m.role==='system').map(m=>m.content).join('\n');return{systemInstruction:sys?{parts:[{text:sys}]}:undefined,contents:q.messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]})),generationConfig:{temperature:q.temperature??.7,maxOutputTokens:q.maxTokens}}}
 async generate(q:ProviderGenerateRequest):Promise<ProviderResponse>{const c=q.credential;if(!c?.apiKey)throw statusError(401);const u=endpoint(this.base(c),`models/${q.modelId}:generateContent`);const r=await safeFetch(u,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':c.apiKey},body:JSON.stringify(this.payload(q))},c.apiKey);if(!r.ok)throw statusError(r.status);const d:any=await r.json();return{content:(d.candidates?.[0]?.content?.parts||[]).map((p:any)=>p.text||'').join(''),modelId:q.modelId}}
 async *stream(q:ProviderGenerateRequest):AsyncIterable<ProviderStreamChunk>{const c=q.credential;if(!c?.apiKey)throw statusError(401);const u=endpoint(this.base(c),`models/${q.modelId}:streamGenerateContent?alt=sse`);const r=await safeFetch(u,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':c.apiKey},body:JSON.stringify(this.payload(q)),signal:q.signal},c.apiKey);if(!r.ok||!r.body)throw statusError(r.status);const reader=r.body.getReader(),dec=new TextDecoder();let buf='';try{while(true){const x=await reader.read();if(x.done)break;buf+=dec.decode(x.value,{stream:true});const frames=buf.split(/\n\n/);buf=frames.pop()||'';for(const frame of frames){const line=frame.split('\n').find(v=>v.startsWith('data:'));if(!line)continue;try{const d:any=JSON.parse(line.slice(5).trim());const candidate=d.candidates?.[0];const text=(candidate?.content?.parts||[]).map((p:any)=>typeof p.text==='string'?p.text:'').join('');if(text)yield{delta:text,isComplete:false};if(candidate?.finishReason==='SAFETY')throw new ProviderError('invalid_response','Gemini blocked this response for safety reasons',400);if(d.usageMetadata)yield{delta:'',isComplete:false,usage:{promptTokens:d.usageMetadata.promptTokenCount||0,completionTokens:d.usageMetadata.candidatesTokenCount||0,totalTokens:d.usageMetadata.totalTokenCount||0}}}catch(e){if(e instanceof ProviderError)throw e;}}}yield{delta:'',isComplete:true};}finally{reader.releaseLock()}}
 getCapabilities():ProviderCapabilities{return{supportsStreaming:true,supportsVision:true,supportsToolCalling:true}}
}
