import type { LLMProvider } from './types.js';
import type { ModelDescriptor,ProviderCapabilities,ProviderCredential,ProviderGenerateRequest,ProviderResponse,ProviderStreamChunk } from '@espera/shared';
import { authHeaders,endpoint,openAIBase,safeFetch,statusError } from './http.js';
export class OpenAIProvider implements LLMProvider {
 readonly id: string='openai'; readonly name: string='OpenAI'; readonly defaultBaseUrl: string='https://api.openai.com/v1';
 async listModels(c?:ProviderCredential):Promise<ModelDescriptor[]>{ if(!c?.apiKey)return []; const r=await safeFetch(endpoint(openAIBase(c.endpointUrl),'models'),{headers:authHeaders(c)},c.apiKey); if(!r.ok)throw statusError(r.status); const d:any=await r.json(); return (d.data||[]).map((m:any)=>({id:m.id,name:m.id,contextWindow:0,supportsStreaming:true,ownedBy:m.owned_by,available:true})).sort((a:any,b:any)=>a.id.localeCompare(b.id)); }
 async validateCredential(c:ProviderCredential){try{return (await this.listModels(c)).length>=0}catch{return false}}
 private url(c?:ProviderCredential){return endpoint(openAIBase(c?.endpointUrl),'chat/completions')}
 async generate(q:ProviderGenerateRequest):Promise<ProviderResponse>{const c=q.credential;if(!c?.apiKey)throw statusError(401);const r=await safeFetch(this.url(c),{method:'POST',headers:{'Content-Type':'application/json',...authHeaders(c)},body:JSON.stringify({model:q.modelId,messages:q.messages,temperature:q.temperature??.7,max_tokens:q.maxTokens})},c.apiKey);if(!r.ok)throw statusError(r.status);const d:any=await r.json();return{content:d.choices?.[0]?.message?.content||'',modelId:q.modelId,usage:d.usage?{promptTokens:d.usage.prompt_tokens,completionTokens:d.usage.completion_tokens,totalTokens:d.usage.total_tokens}:undefined}}
 async *stream(q:ProviderGenerateRequest):AsyncIterable<ProviderStreamChunk>{const c=q.credential;if(!c?.apiKey)throw statusError(401);const r=await safeFetch(this.url(c),{method:'POST',headers:{'Content-Type':'application/json',...authHeaders(c)},body:JSON.stringify({model:q.modelId,messages:q.messages,temperature:q.temperature??.7,max_tokens:q.maxTokens,stream:true})},c.apiKey);if(!r.ok||!r.body)throw statusError(r.status);const reader=r.body.getReader(),dec=new TextDecoder();let buf='';while(true){const x=await reader.read();if(x.done)break;buf+=dec.decode(x.value,{stream:true});const lines=buf.split('\n');buf=lines.pop()||'';for(const l of lines){if(!l.startsWith('data:'))continue;const s=l.slice(5).trim();if(s==='[DONE]'){yield{delta:'',isComplete:true};return}try{const d=JSON.parse(s),v=d.choices?.[0]?.delta?.content;if(v)yield{delta:v,isComplete:false}}catch{}}}yield{delta:'',isComplete:true}}
 getCapabilities():ProviderCapabilities{return{supportsStreaming:true,supportsVision:true,supportsToolCalling:true}}
}
export class OpenAICompatibleProvider extends OpenAIProvider { readonly id='openai-compatible'; readonly name='OpenAI Compatible'; readonly defaultBaseUrl='http://localhost:1234/v1'; }
