import React,{useState} from 'react'; import { Sliders,ShieldCheck,Key,RefreshCw,Trash2 } from 'lucide-react'; import type {SessionState,ProviderConnection} from '../../stores/session.js'; import type {ProviderInfo} from '../../services/api.js'; import {api} from '../../services/api.js';
export const SettingsView:React.FC<{session:SessionState;onUpdateSession:(p:Partial<SessionState>)=>void;providers:ProviderInfo[]}>=({session,onUpdateSession,providers})=>{
 const [providerId,setProviderId]=useState('openai-compatible'),[name,setName]=useState('내 API 연결'),[baseUrl,setBaseUrl]=useState('http://localhost:1234/v1'),[key,setKey]=useState(''),[manual,setManual]=useState(''),[models,setModels]=useState<any[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const definition=providers.find(p=>p.id===providerId);
 function changeProvider(id:string){setProviderId(id);const p=providers.find(x=>x.id===id);setBaseUrl(p?.defaultBaseUrl||'');setModels([]);setStatus('');}
 async function discover(){setBusy(true);setStatus('');try{const ms=providerId==='mock'?(definition?.models||[]):await api.listModels(providerId,key,baseUrl||undefined);setModels(ms);setStatus(`${ms.length}개 모델을 불러왔습니다.`)}catch(e:any){setStatus(e.message)}finally{setBusy(false)}}
 function save(){const extra=manual.trim()? [{id:manual.trim(),name:manual.trim(),contextWindow:0,supportsStreaming:true}]:[];const all=[...models,...extra.filter(x=>!models.some(m=>m.id===x.id))];if(!all.length){setStatus('모델 목록을 조회하거나 수동 모델 ID를 입력하세요.');return}const id=crypto.randomUUID();const conn:ProviderConnection={id,name:name||providerId,providerId,baseUrl:baseUrl||undefined,models:all};onUpdateSession({connections:[...session.connections,conn],apiKeys:{...session.apiKeys,[id]:key},connectionId:id,providerId,modelId:all[0].id});setKey('');setManual('');setStatus('연결을 현재 탭 메모리에 추가했습니다. 새로고침하면 API Key는 폐기됩니다.')}
 function remove(id:string){const keys={...session.apiKeys};delete keys[id];onUpdateSession({connections:session.connections.filter(c=>c.id!==id),apiKeys:keys,connectionId:'mock',providerId:'mock',modelId:'mock-model-a'})}
 return <div className="flex-1 p-4 sm:p-6 max-w-5xl mx-auto w-full overflow-y-auto space-y-6"><div><h1 className="text-xl font-bold flex gap-2"><Sliders className="text-sky-400"/>Provider 연결</h1><p className="text-xs text-slate-400">Endpoint + API Key로 모델을 조회하고 채팅에 연결합니다.</p></div>
 <div className="p-4 rounded-xl border border-sky-800 bg-sky-950/30 text-xs flex gap-3"><ShieldCheck className="text-sky-400 shrink-0"/><span>API Key는 Web Storage·D1에 저장되지 않고 현재 페이지 메모리에만 있습니다. 새로고침하면 다시 입력해야 합니다. 비밀은 POST 헤더로만 백엔드에 전달됩니다.</span></div>
 <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4"><h2 className="font-semibold text-sm">새 연결</h2><div className="grid sm:grid-cols-2 gap-3">
 <label className="text-xs">Provider<select className="field" value={providerId} onChange={e=>changeProvider(e.target.value)}>{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label className="text-xs">연결 이름<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label>
 <label className="text-xs sm:col-span-2">API Base URL<input className="field font-mono" value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://…/v1"/></label>
 <label className="text-xs sm:col-span-2"><Key className="inline w-3"/> API Key<input type="password" autoComplete="off" className="field font-mono" value={key} onChange={e=>setKey(e.target.value)} placeholder={providerId==='mock'?'Mock은 불필요':'현재 탭에만 보관'}/></label></div>
 <div className="flex gap-2"><button className="btn" disabled={busy||(!key&&providerId!=='mock')} onClick={discover}><RefreshCw className={`w-4 ${busy?'animate-spin':''}`}/>모델 조회</button></div>
 {models.length>0&&<div className="max-h-48 overflow-auto border border-slate-700 rounded-lg p-2 text-xs">{models.map(m=><div key={m.id} className="py-1 border-b border-slate-800">{m.name} <span className="text-slate-500">{m.id}</span></div>)}</div>}
 <label className="text-xs">수동 모델 ID (목록 API 미지원 시)<input className="field" value={manual} onChange={e=>setManual(e.target.value)}/></label><button className="btn bg-sky-600" onClick={save}>연결 적용</button>{status&&<p className="text-xs text-amber-300">{status}</p>}</div>
 <div className="space-y-2"><h2 className="font-semibold">현재 탭 연결</h2>{session.connections.length===0?<p className="text-xs text-slate-500">추가 연결 없음</p>:session.connections.map(c=><div key={c.id} className="p-3 bg-slate-900 border border-slate-800 rounded-xl flex justify-between"><div><b>{c.name}</b><p className="text-xs text-slate-400">{c.providerId} · {c.models.length} models · {c.baseUrl}</p></div><button onClick={()=>remove(c.id)}><Trash2 className="w-4 text-rose-400"/></button></div>)}</div></div>}
