import React, { useState } from 'react';
import { Key, RefreshCw, ShieldCheck, Sliders, Trash2 } from 'lucide-react';
import type { ModelDescriptor } from '@espera/shared';
import type { ProviderInfo } from '../../services/api.js';
import { api } from '../../services/api.js';
import type { ProviderConnection, SessionState } from '../../stores/session.js';
import { useLanguage } from '../../i18n.js';
interface Props { session: SessionState; onUpdateSession: (patch: Partial<SessionState>) => void; providers: ProviderInfo[]; }
export const SettingsView: React.FC<Props> = ({ session, onUpdateSession, providers }) => {
  const { language, setLanguage, t } = useLanguage(); const [providerId, setProviderId] = useState('openai-compatible'); const [name, setName] = useState('Local API connection'); const [baseUrl, setBaseUrl] = useState('http://localhost:1234/v1'); const [key, setKey] = useState(''); const [manualModel, setManualModel] = useState(''); const [models, setModels] = useState<ModelDescriptor[]>([]); const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false); const definition = providers.find((provider) => provider.id === providerId);
  function changeProvider(id: string) { setProviderId(id); setBaseUrl(providers.find((provider) => provider.id === id)?.defaultBaseUrl || ''); setModels([]); setStatus(''); }
  async function discoverModels() { setBusy(true); setStatus('Loading models…'); try { const discovered = providerId === 'mock' ? (definition?.models || []) : await api.listModels(providerId, key, baseUrl || undefined); setModels(discovered); setStatus(`${discovered.length} model(s) loaded.`); } catch (error) { setStatus(error instanceof Error ? error.message : 'Model discovery failed.'); } finally { setBusy(false); } }
  async function saveConnection() { const manual = manualModel.trim() ? [{ id: manualModel.trim(), name: manualModel.trim(), contextWindow: 0, supportsStreaming: true }] : []; const allModels = [...models, ...manual.filter((item) => !models.some((model) => model.id === item.id))]; if (!allModels.length) { setStatus('Discover models or enter a manual model ID first.'); return; } setBusy(true); try { const id = crypto.randomUUID(); const persisted = await api.saveProviderConnection({ id, name: name.trim() || providerId, providerId, baseUrl: baseUrl.trim() || undefined, models: allModels }); const connection: ProviderConnection = persisted; onUpdateSession({ connections: [...session.connections, connection], apiKeys: { ...session.apiKeys, [id]: key }, connectionId: id, providerId, modelId: allModels[0].id }); setKey(''); setManualModel(''); setStatus('Connection saved. The API key remains in this tab only.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Connection could not be saved.'); } finally { setBusy(false); } }
  async function removeConnection(id: string) { if (!window.confirm('Delete this provider connection metadata?')) return; setBusy(true); try { await api.deleteProviderConnection(id); const apiKeys = { ...session.apiKeys }; delete apiKeys[id]; onUpdateSession({ connections: session.connections.filter((connection) => connection.id !== id), apiKeys, connectionId: 'mock', providerId: 'mock', modelId: 'mock-model-a' }); setStatus('Connection deleted.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Connection could not be deleted.'); } finally { setBusy(false); } }
  return <main className="workspace-page"><header className="workspace-header"><div><div className="workspace-eyebrow">Control center</div><h1 className="workspace-title">{t('settings.title')}</h1><p className="workspace-subtitle">Manage language, model connections, and the credentials that stay only in this browser tab.</p></div><Sliders className="mt-1 h-5 w-5 text-neutral-600" /></header>
    <div className="mt-7 space-y-6"><section className="workspace-section"><div className="workspace-section-header"><div><h2 className="workspace-section-title">{t('settings.language')}</h2><p className="workspace-section-copy">{t('settings.language.help')}</p></div><div className="flex rounded-lg border border-neutral-700 bg-neutral-950 p-1" role="group" aria-label={t('settings.language')}><button type="button" onClick={() => setLanguage('ko')} className={`rounded-md px-3 py-1.5 text-xs transition ${language === 'ko' ? 'bg-neutral-200 text-neutral-900' : 'text-neutral-500 hover:text-neutral-200'}`}>{t('settings.korean')}</button><button type="button" onClick={() => setLanguage('en')} className={`rounded-md px-3 py-1.5 text-xs transition ${language === 'en' ? 'bg-neutral-200 text-neutral-900' : 'text-neutral-500 hover:text-neutral-200'}`}>{t('settings.english')}</button></div></div></section>
      <section className="flex gap-3 rounded-xl border border-neutral-800 bg-neutral-900/40 p-4"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-neutral-300" /><div><p className="text-xs font-medium text-neutral-200">Bring your own key, keep control</p><p className="mt-1 text-xs leading-5 text-neutral-500">Keys are never written to D1, Web Storage, URLs, logs, or context runs. After a reload, re-enter the key before using a non-Mock provider.</p></div></section>
      <section className="workspace-section"><div className="workspace-section-header"><div><h2 className="workspace-section-title">{t('settings.addConnection')}</h2><p className="workspace-section-copy">Connect a provider without giving Espera permanent access to your key.</p></div></div><div className="grid gap-4 p-5 sm:grid-cols-2"><label className="block text-xs font-medium text-neutral-400">{t('settings.provider')}<select className="workspace-input mt-2" value={providerId} onChange={(event) => changeProvider(event.target.value)}>{providers.map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label><label className="block text-xs font-medium text-neutral-400">{t('settings.connectionName')}<input className="workspace-input mt-2" value={name} onChange={(event) => setName(event.target.value)} /></label><label className="block text-xs font-medium text-neutral-400 sm:col-span-2">{t('settings.baseUrl')}<input className="workspace-input mt-2 font-mono" value={baseUrl} onChange={(event) => setBaseUrl(event.target.value)} placeholder="https://api.example.com/v1" /></label><label className="block text-xs font-medium text-neutral-400 sm:col-span-2"><Key className="mr-1 inline h-3 w-3" />{t('settings.apiKey')}<input type="password" autoComplete="off" className="workspace-input mt-2 font-mono" value={key} onChange={(event) => setKey(event.target.value)} placeholder={providerId === 'mock' ? 'Not required for Mock' : 'Required for discovery and chat'} /></label><label className="block text-xs font-medium text-neutral-400 sm:col-span-2">Manual model ID <input className="workspace-input mt-2 font-mono" value={manualModel} onChange={(event) => setManualModel(event.target.value)} placeholder="For servers without a models endpoint" /></label></div><div className="flex flex-wrap gap-2 border-t border-neutral-800 px-5 py-4"><button className="workspace-button" disabled={busy || (!key && providerId !== 'mock')} onClick={discoverModels}><RefreshCw className={busy ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /> {t('settings.discover')}</button><button className="workspace-button workspace-button-primary" disabled={busy} onClick={saveConnection}>{t('settings.save')}</button>{status && <p className="self-center text-xs text-neutral-400" role="status">{status}</p>}</div>{models.length > 0 && <div className="mx-5 mb-5 max-h-48 overflow-auto rounded-lg border border-neutral-800 bg-neutral-950 p-2 text-xs text-neutral-400">{models.map((model) => <div key={model.id} className="border-b border-neutral-800 px-2 py-2 last:border-0"><span className="text-neutral-200">{model.name}</span><span className="ml-2 font-mono text-neutral-600">{model.id}</span></div>)}</div>}</section>
      <section className="workspace-section"><div className="workspace-section-header"><div><h2 className="workspace-section-title">{t('settings.saved')}</h2><p className="workspace-section-copy">Metadata persists per account; credentials do not.</p></div></div>{session.connections.length === 0 ? <p className="p-5 text-sm text-neutral-500">{t('settings.none')}</p> : <div className="divide-y divide-neutral-800">{session.connections.map((connection) => <div key={connection.id} className="flex items-start justify-between gap-4 px-5 py-4"><div className="min-w-0"><p className="text-sm font-medium text-neutral-100">{connection.name}</p><p className="mt-1 truncate text-xs text-neutral-500">{connection.providerId} · {connection.models.length} models · {connection.baseUrl || 'default endpoint'}</p><p className="mt-2 text-[11px] text-neutral-600">{session.apiKeys[connection.id] ? 'Key available in this tab' : 'Key re-entry required'}</p></div><button className="rounded-lg p-2 text-neutral-600 transition hover:bg-red-950/40 hover:text-red-300" aria-label={`Delete ${connection.name}`} onClick={() => removeConnection(connection.id)}><Trash2 className="h-4 w-4" /></button></div>)}</div>}</section>
    </div>
  </main>;
};
