import React, { createContext, useContext, useMemo, useState } from 'react';

export type Language = 'ko' | 'en';
type Dictionary = Record<string, string>;

const dictionaries: Record<Language, Dictionary> = {
  ko: {
    'brand.tagline': '모든 모델을 가로지르는 나의 맥락',
    'nav.chat': '채팅', 'nav.memory': '메모리', 'nav.persona': '페르소나', 'nav.projects': '프로젝트', 'nav.settings': '설정', 'nav.inspector': '컨텍스트 검사기',
    'chat.conversations': '대화 목록', 'chat.emptyConversations': '아직 대화가 없습니다.', 'chat.new': '새 채팅', 'chat.global': '전체 맥락', 'chat.conversation': '대화', 'chat.empty.title': '무엇을 함께 해볼까요?', 'chat.delete': '대화 삭제', 'chat.deleteConfirm': '이 대화를 삭제할까요? 대화와 메시지가 모두 삭제됩니다.', 'chat.deleted': '대화가 삭제되었습니다.',
    'chat.empty.body': 'Espera는 중요한 프로젝트와 선호를 메모리 후보로 제안합니다. 승인한 메모리는 어떤 AI 모델에서도 이어집니다.',
    'chat.prompt.memory': '내가 기억된 내용을 보여줘', 'chat.prompt.plan': '이번 주 계획을 세워줘', 'chat.prompt.project': 'Project Espera를 설명해줘',
    'chat.placeholder': 'Espera에게 메시지 보내기…', 'chat.disclaimer': 'Espera는 실수할 수 있습니다. 중요한 메모리는 승인하기 전에 확인하세요.', 'chat.streaming': '응답 생성 중…', 'chat.retry': '다시 시도',
    'memory.title': '메모리', 'memory.subtitle': '제안된 메모리를 검토하고 장기 맥락에 포함할 정보를 선택하세요.', 'memory.add': '메모리 추가', 'memory.pending': '검토 대기', 'memory.active': '활성 메모리', 'memory.history': '기록', 'memory.search': '메모리 검색…',
    'persona.title': '페르소나', 'persona.subtitle': 'AI가 나를 대하고 응답하는 방식을 직접 정의하세요.', 'persona.edit': '페르소나 편집',
    'projects.title': '프로젝트', 'projects.subtitle': '장기 작업을 프로젝트별 메모리와 맥락으로 분리해 관리하세요.', 'projects.create': '프로젝트 만들기', 'projects.name': '프로젝트 이름', 'projects.description': '이 프로젝트에 포함할 내용', 'projects.empty': '아직 프로젝트가 없습니다.',
    'settings.title': '설정', 'settings.language': '언어', 'settings.language.help': 'Espera 전체에서 사용할 언어를 선택하세요.', 'settings.korean': '한국어', 'settings.english': 'English',
    'settings.providers': 'Provider 연결', 'settings.providers.help': 'API Key는 현재 브라우저 탭에서만 사용되며 저장되지 않습니다.', 'settings.addConnection': '연결 추가', 'settings.provider': 'Provider', 'settings.connectionName': '연결 이름', 'settings.baseUrl': 'API Base URL', 'settings.apiKey': 'API Key', 'settings.discover': '모델 불러오기', 'settings.save': '연결 저장', 'settings.saved': '저장된 연결', 'settings.none': '저장된 연결이 없습니다.',
    'auth.welcome': 'Espera에 오신 것을 환영합니다', 'auth.body': '대화, 메모리, 개인 AI 맥락을 하나의 비공개 workspace에서 관리하세요.', 'auth.github': 'GitHub로 계속하기', 'auth.notConfigured': 'GitHub 로그인이 아직 설정되지 않았습니다.',
    'common.workspace': 'Workspace', 'common.account': '계정', 'common.loading': '불러오는 중…', 'common.cancel': '취소', 'common.save': '저장', 'common.close': '닫기', 'common.delete': '삭제', 'common.details': '상세 보기', 'common.updated': '업데이트',
    'projects.library': '프로젝트 목록', 'projects.libraryCopy': '대화와 메모리를 맥락별로 정리하세요.', 'projects.createCopy': '작업을 위한 개인 맥락을 만드세요.', 'projects.noDescription': '설명이 없습니다.', 'projects.emptyCopy': '첫 프로젝트를 만들어 대화에 맥락을 부여하세요.', 'projects.updated': '업데이트',
    'memory.continuity': '지속성 계층', 'memory.reviewQueue': '검토 대기열', 'memory.activeView': '활성 메모리', 'memory.historyView': '메모리 기록', 'memory.count': '개 · 활성 메모리만 모델 맥락에 포함됩니다.', 'memory.loading': '메모리를 불러오는 중…', 'memory.empty': '이 보기에 메모리가 없습니다.', 'memory.emptyCopy': '대화 후 메모리 후보가 여기에 표시됩니다.', 'memory.confidence': '신뢰도', 'memory.updated': '업데이트', 'memory.edit': '메모리 편집', 'memory.addTitle': '메모리 추가', 'memory.statement': '내용', 'memory.relationship': '관계', 'memory.evidence': '근거', 'memory.noEvidence': '기록된 근거가 없습니다.', 'memory.revisions': '변경 이력', 'memory.archive': '메모리 보관', 'memory.save': '저장',
    'persona.identity': '정체성 계층', 'persona.editTitle': '페르소나 편집', 'persona.editCopy': '변경사항은 새 버전으로 저장되며 이후 대화에 적용됩니다.', 'persona.name': '이름', 'persona.reason': '변경 사유', 'persona.instructions': '지침', 'persona.tone': '말투와 태도', 'persona.principles': '핵심 원칙', 'persona.principlesHint': '(한 줄에 하나씩)', 'persona.saveRevision': '버전 저장', 'persona.previewTitle': 'Espera가 나를 대하는 방식', 'persona.previewCopy': 'AI의 추측이 아닌 사용자가 관리하는 맥락입니다.', 'persona.revisions': '변경 이력', 'persona.revisionsCopy': '모든 변경은 추적됩니다.',
    'settings.control': '제어 센터', 'settings.subtitle': '언어, 모델 연결, 이 브라우저 탭에만 유지되는 자격 증명을 관리하세요.', 'settings.keyTitle': '내 API Key를 사용하고 직접 통제하세요', 'settings.keyCopy': 'Key는 D1, Web Storage, URL, 로그, Context Run에 저장되지 않습니다. 새로고침 후에는 외부 Provider를 사용하기 전에 Key를 다시 입력하세요.', 'settings.addCopy': 'Espera에 영구적으로 Key를 맡기지 않고 Provider를 연결하세요.', 'settings.manualModel': '수동 모델 ID', 'settings.manualModelHint': '모델 목록 API가 없는 서버용', 'settings.notRequiredMock': 'Mock에는 필요하지 않습니다', 'settings.requiredDiscovery': '모델 조회와 채팅에 필요합니다', 'settings.savedCopy': '연결 정보는 계정에 저장되지만 자격 증명은 저장되지 않습니다.', 'settings.keyAvailable': '이 탭에서 Key 사용 가능', 'settings.keyRequired': 'Key 재입력 필요', 'settings.modelsLoaded': '개 모델을 불러왔습니다.', 'settings.loadingModels': '모델을 불러오는 중…', 'settings.discoverFirst': '모델을 불러오거나 수동 모델 ID를 입력하세요.', 'settings.compatibleHint': '공개 HTTPS OpenAI-compatible endpoint를 지원합니다.',
    'common.signOut': '로그아웃', 'common.githubAccount': 'GitHub 계정', 'inspector.title': '컨텍스트 검사기', 'inspector.badge': '읽기 전용 감사', 'inspector.subtitle': '이 대화가 모델에 전달되기 직전에 조합된 컨텍스트를 확인합니다.', 'inspector.security': 'API Key와 인증 정보는 이 검사기에 표시되지 않습니다.', 'inspector.loading': '컨텍스트를 불러오는 중…', 'inspector.empty': '아직 기록된 Context Run이 없습니다.', 'inspector.emptyCopy': '대화에서 메시지를 한 번 전송하면 여기에 컨텍스트 구성이 표시됩니다.', 'inspector.provider': 'Provider · 모델', 'inspector.persona': '페르소나 버전', 'inspector.memories': '선택된 메모리', 'inspector.tokens': '예상 토큰', 'inspector.selection': '메모리 선택 이유', 'inspector.noMemories': '선택된 활성 메모리가 없습니다.', 'inspector.assembly': '프롬프트 구성', 'inspector.showFull': '전체 보기', 'inspector.showSummary': '요약 보기', 'inspector.chooseConversation': '먼저 대화를 선택하세요.',
  },
  en: {
    'brand.tagline': 'Your context, across every model',
    'nav.chat': 'Chat', 'nav.memory': 'Memory', 'nav.persona': 'Persona', 'nav.projects': 'Projects', 'nav.settings': 'Settings', 'nav.inspector': 'Context inspector',
    'chat.conversations': 'Conversations', 'chat.emptyConversations': 'No conversations yet.', 'chat.new': 'New chat', 'chat.global': 'Global context', 'chat.conversation': 'Conversation', 'chat.empty.title': 'What shall we work on?', 'chat.delete': 'Delete conversation', 'chat.deleteConfirm': 'Delete this conversation and all of its messages?', 'chat.deleted': 'Conversation deleted.',
    'chat.empty.body': 'Espera proposes important projects and preferences as memories. Approved memories continue across every AI model.', 'chat.prompt.memory': 'Show me what you remember', 'chat.prompt.plan': 'Help me plan this week', 'chat.prompt.project': 'Explain Project Espera', 'chat.placeholder': 'Message Espera…', 'chat.disclaimer': 'Espera can make mistakes. Review important memories before approving them.', 'chat.streaming': 'Generating response…', 'chat.retry': 'Retry',
    'memory.title': 'Memory', 'memory.subtitle': 'Review proposed memories and choose what becomes part of your long-term context.', 'memory.add': 'Add memory', 'memory.pending': 'Review queue', 'memory.active': 'Active', 'memory.history': 'History', 'memory.search': 'Search memories…',
    'persona.title': 'Persona', 'persona.subtitle': 'Define how your AI should treat you and respond to you.', 'persona.edit': 'Edit persona', 'projects.title': 'Projects', 'projects.subtitle': 'Keep long-running work separate with project-scoped memory and context.', 'projects.create': 'Create project', 'projects.name': 'Project name', 'projects.description': 'What belongs in this project?', 'projects.empty': 'No projects yet.',
    'settings.title': 'Settings', 'settings.language': 'Language', 'settings.language.help': 'Choose the language used throughout Espera.', 'settings.korean': '한국어', 'settings.english': 'English', 'settings.providers': 'Provider connections', 'settings.providers.help': 'API keys are used only in this browser tab and are never stored.', 'settings.addConnection': 'Add connection', 'settings.provider': 'Provider', 'settings.connectionName': 'Connection name', 'settings.baseUrl': 'API base URL', 'settings.apiKey': 'API key', 'settings.discover': 'Discover models', 'settings.save': 'Save connection', 'settings.saved': 'Saved connections', 'settings.none': 'No saved connections yet.', 'auth.welcome': 'Welcome to Espera', 'auth.body': 'Your conversations, memory, and personal AI context in one private workspace.', 'auth.github': 'Continue with GitHub', 'auth.notConfigured': 'GitHub sign-in is not configured yet.',
    'common.workspace': 'Workspace', 'common.account': 'Account', 'common.loading': 'Loading…', 'common.cancel': 'Cancel', 'common.save': 'Save', 'common.close': 'Close', 'common.delete': 'Delete', 'common.details': 'Details', 'common.updated': 'Updated', 'projects.library': 'Project library', 'projects.libraryCopy': 'Keep conversations and memories organized by context.', 'projects.createCopy': 'A private context for your work.', 'projects.noDescription': 'No description yet.', 'projects.emptyCopy': 'Create your first project to give conversations a home.', 'projects.updated': 'Updated',
    'memory.continuity': 'Continuity layer', 'memory.reviewQueue': 'Review queue', 'memory.activeView': 'Active memory', 'memory.historyView': 'Memory history', 'memory.count': 'items · Only active memories enter model context.', 'memory.loading': 'Loading memories…', 'memory.empty': 'No memories in this view.', 'memory.emptyCopy': 'Pending candidates appear here after a conversation.', 'memory.confidence': 'confidence', 'memory.updated': 'updated', 'memory.edit': 'Edit memory', 'memory.addTitle': 'Add memory', 'memory.statement': 'Statement', 'memory.relationship': 'Relationship', 'memory.evidence': 'Evidence', 'memory.noEvidence': 'No evidence recorded.', 'memory.revisions': 'Revision history', 'memory.archive': 'Archive memory', 'memory.save': 'Save',
    'persona.identity': 'Identity layer', 'persona.editTitle': 'Edit persona', 'persona.editCopy': 'Changes create a new revision and affect future conversations.', 'persona.name': 'Name', 'persona.reason': 'Change reason', 'persona.instructions': 'Instructions', 'persona.tone': 'Tone & manner', 'persona.principles': 'Core principles', 'persona.principlesHint': '(one per line)', 'persona.saveRevision': 'Save revision', 'persona.previewTitle': 'How Espera should work with you', 'persona.previewCopy': 'This is user-controlled context, not an AI guess.', 'persona.revisions': 'Revision history', 'persona.revisionsCopy': 'Every change is traceable.',
    'settings.control': 'Control center', 'settings.subtitle': 'Manage language, model connections, and the credentials that stay only in this browser tab.', 'settings.keyTitle': 'Bring your own key, keep control', 'settings.keyCopy': 'Keys are never written to D1, Web Storage, URLs, logs, or context runs. After a reload, re-enter the key before using a non-Mock provider.', 'settings.addCopy': 'Connect a provider without giving Espera permanent access to your key.', 'settings.manualModel': 'Manual model ID', 'settings.manualModelHint': 'For servers without a models endpoint', 'settings.notRequiredMock': 'Not required for Mock', 'settings.requiredDiscovery': 'Required for discovery and chat', 'settings.savedCopy': 'Metadata persists per account; credentials do not.', 'settings.keyAvailable': 'Key available in this tab', 'settings.keyRequired': 'Key re-entry required', 'settings.modelsLoaded': 'model(s) loaded.', 'settings.loadingModels': 'Loading models…', 'settings.discoverFirst': 'Discover models or enter a manual model ID first.', 'settings.compatibleHint': 'Public HTTPS OpenAI-compatible endpoints are supported.',
    'common.signOut': 'Sign out', 'common.githubAccount': 'GitHub account', 'inspector.title': 'Context inspector', 'inspector.badge': 'Read-only audit', 'inspector.subtitle': 'Inspect the context assembled immediately before this conversation is sent to the model.', 'inspector.security': 'API keys and authentication data are never shown in this inspector.', 'inspector.loading': 'Loading context…', 'inspector.empty': 'No Context Run has been recorded yet.', 'inspector.emptyCopy': 'Send a message in this conversation to see how its context was assembled.', 'inspector.provider': 'Provider · model', 'inspector.persona': 'Persona version', 'inspector.memories': 'Selected memories', 'inspector.tokens': 'Estimated tokens', 'inspector.selection': 'Why these memories were selected', 'inspector.noMemories': 'No active memories were selected.', 'inspector.assembly': 'Prompt assembly', 'inspector.showFull': 'Show full', 'inspector.showSummary': 'Show summary', 'inspector.chooseConversation': 'Select a conversation first.',
  },
};

interface LanguageContextValue { language: Language; setLanguage: (language: Language) => void; t: (key: string) => string; }
const LanguageContext = createContext<LanguageContextValue | null>(null);
const STORAGE_KEY = 'espera_language';
export function LanguageProvider({ children }: { children: React.ReactNode }) { const [language, setLanguageState] = useState<Language>(() => { try { return localStorage.getItem(STORAGE_KEY) === 'en' ? 'en' : 'ko'; } catch { return 'ko'; } }); const setLanguage = (next: Language) => { setLanguageState(next); try { localStorage.setItem(STORAGE_KEY, next); } catch { /* unavailable */ } }; const value = useMemo(() => ({ language, setLanguage, t: (key: string) => dictionaries[language][key] || dictionaries.en[key] || key }), [language]); return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>; }
export function useLanguage(): LanguageContextValue { const context = useContext(LanguageContext); if (!context) throw new Error('useLanguage must be used inside LanguageProvider'); return context; }
