import { Hono } from 'hono';
import type { ContentfulStatusCode } from 'hono/utils/http-status';
import { ValidateProviderCredentialSchema } from '@espera/shared';
import type { ProviderRegistry } from '../providers/registry.js';
import { maskApiKey } from '../security/crypto.js';
import { ProviderError } from '../providers/http.js';
import { UserRepository } from '../db/repositories/user.repo.js';
import { ProviderConnectionRepository } from '../db/repositories/provider-connection.repo.js';
import type { D1Database } from '../db/d1-interface.js';
export function createProviderRoutes(db: D1Database, registry:ProviderRegistry){const r=new Hono();
 const userId = 'user_default';
 const userRepo = new UserRepository(db);
 const connectionRepo = new ProviderConnectionRepository(db);
 r.get('/',async c=>c.json({providers:await Promise.all(registry.list().map(async p=>({id:p.id,name:p.name,defaultBaseUrl:p.defaultBaseUrl,models:p.id==='mock'?await p.listModels():[],capabilities:p.getCapabilities()})))}));
 r.post('/models',async c=>{try{const b:any=await c.req.json();if(!b.providerId||(!b.credential?.apiKey&&b.providerId!=='mock'))return c.json({error:{code:'invalid_credential',message:'API Key가 필요합니다.'}},400);const models=await registry.get(b.providerId).listModels(b.credential);return c.json({models});}catch(e){const x=e as any;return c.json({error:{code:x.code||'provider_unavailable',message:x.message||'모델 목록을 불러오지 못했습니다.'}},(x.status||502) as ContentfulStatusCode)}});
 r.post('/validate',async c=>{const parsed=ValidateProviderCredentialSchema.safeParse(await c.req.json());if(!parsed.success)return c.json({error:'Validation failed',details:parsed.error.flatten()},400);try{const {providerId,credential}=parsed.data;const isValid=await registry.get(providerId).validateCredential(credential);return c.json({providerId,isValid,maskedKey:maskApiKey(credential.apiKey),testedAt:new Date().toISOString()});}catch(e){const x=e as ProviderError;return c.json({error:{code:x.code||'unknown_error',message:x.message}},(x.status||502) as ContentfulStatusCode)}});
 r.get('/connections', async c=>{await userRepo.ensureUser(userId, 'Espera User'); return c.json({connections:await connectionRepo.list(userId)});});
 r.post('/connections', async c=>{const body:any=await c.req.json().catch(()=>({}));if(!body.name||!body.providerId||!Array.isArray(body.models))return c.json({error:'name, providerId, and models are required'},400);if(!registry.list().some(p=>p.id===body.providerId))return c.json({error:'Unknown provider'},400);await userRepo.ensureUser(userId,'Espera User');const connection=await connectionRepo.upsert({id:body.id,userId,name:String(body.name).slice(0,100),providerId:body.providerId,baseUrl:body.baseUrl?String(body.baseUrl).slice(0,2048):null,status:body.status==='error'?'error':'active',lastTestedAt:body.lastTestedAt||null,models:body.models.slice(0,200).map((model:any)=>({id:String(model.id),name:String(model.name||model.id),contextWindow:Number(model.contextWindow)||0,supportsStreaming:model.supportsStreaming!==false}))});return c.json({connection},201);});
 r.delete('/connections/:id', async c=>{await userRepo.ensureUser(userId,'Espera User');const removed=await connectionRepo.remove(c.req.param('id'),userId);return removed?c.body(null,204):c.json({error:'Connection not found'},404);});
 return r;}
