import React, { useEffect, useState } from 'react';
import { FolderKanban, Plus, Trash2 } from 'lucide-react';
import type { Project } from '@espera/shared';
import { api } from '../../services/api.js';
import { useLanguage } from '../../i18n.js';

export const ProjectsView: React.FC = () => {
  const { t } = useLanguage();
  const [projects, setProjects] = useState<Project[]>([]);
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [status, setStatus] = useState('');
  const [creating, setCreating] = useState(false);
  async function load() { try { setProjects(await api.getProjects()); } catch (error) { setStatus(error instanceof Error ? error.message : 'Projects could not be loaded.'); } }
  useEffect(() => { void load(); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); if (!name.trim() || creating) return; setCreating(true); setStatus(''); try { const project = await api.createProject(name.trim(), description.trim()); setProjects((current) => [project, ...current]); setName(''); setDescription(''); setStatus('Project created.'); } catch (error) { setStatus(error instanceof Error ? error.message : 'Project could not be created.'); } finally { setCreating(false); } }
  async function remove(project: Project) { if (!window.confirm(`Delete “${project.name}”? Conversations will remain but lose this scope.`)) return; try { await api.deleteProject(project.id); setProjects((current) => current.filter((item) => item.id !== project.id)); } catch (error) { setStatus(error instanceof Error ? error.message : 'Project could not be deleted.'); } }
  return <main className="workspace-page">
    <header className="workspace-header"><div><div className="workspace-eyebrow">{t('common.workspace')}</div><h1 className="workspace-title">{t('projects.title')}</h1><p className="workspace-subtitle">{t('projects.subtitle')}</p></div><button aria-label="Focus project form" className="workspace-button workspace-button-primary" type="button" onClick={() => document.getElementById('create-project-name')?.focus()}><Plus className="h-4 w-4" /> {t('projects.create')}</button></header>
    <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(260px,340px)]">
      <section className="workspace-section min-h-[220px]"><div className="workspace-section-header"><div><h2 className="workspace-section-title">{t('projects.library')}</h2><p className="workspace-section-copy">{t('projects.libraryCopy')}</p></div><span className="workspace-muted">{projects.length}</span></div><div className="divide-y divide-neutral-800">{projects.length === 0 && <div className="px-5 py-16 text-center"><FolderKanban className="mx-auto h-8 w-8 text-neutral-700" /><p className="mt-3 text-sm text-neutral-400">{t('projects.empty')}</p><p className="mt-1 text-xs text-neutral-600">{t('projects.emptyCopy')}</p></div>}{projects.map((project) => <article key={project.id} className="flex items-start justify-between gap-4 px-5 py-4 transition hover:bg-white/[.02]"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-medium text-neutral-100">{project.name}</h3><span className="rounded-full border border-neutral-700 px-2 py-0.5 text-[10px] text-neutral-500">{project.status}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-neutral-500">{project.description || t('projects.noDescription')}</p><p className="mt-2 text-[11px] text-neutral-700">{t('projects.updated')} {new Date(project.updatedAt).toLocaleDateString()}</p></div><button aria-label={`${t('common.delete')} ${project.name}`} className="rounded-lg p-2 text-neutral-600 transition hover:bg-red-950/40 hover:text-red-300" onClick={() => remove(project)}><Trash2 className="h-4 w-4" /></button></article>)}</div></section>
      <form onSubmit={create} className="workspace-section h-fit p-5"><div className="mb-5 flex items-center gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-neutral-800"><Plus className="h-4 w-4 text-neutral-300" /></div><div><h2 className="workspace-section-title">{t('projects.create')}</h2><p className="workspace-section-copy">{t('projects.createCopy')}</p></div></div><label className="mb-4 block text-xs font-medium text-neutral-400">{t('projects.name')}<input id="create-project-name" className="workspace-input mt-2" value={name} onChange={(event) => setName(event.target.value)} placeholder={t('projects.name')} maxLength={100} required /></label><label className="mb-4 block text-xs font-medium text-neutral-400">{t('projects.description')}<textarea className="workspace-input mt-2 resize-none" value={description} onChange={(event) => setDescription(event.target.value)} placeholder={t('projects.description')} maxLength={2000} rows={4} /></label><button className="workspace-button workspace-button-primary w-full" type="submit" disabled={creating}><Plus className="h-4 w-4" /> {creating ? t('common.loading') : t('projects.create')}</button>{status && <p className="mt-3 text-xs text-neutral-400" role="status">{status}</p>}</form>
    </div>
  </main>;
};
